version: '3.8'

services:
  # Next.js Frontend Application
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SIGNALING_SERVER_URL=ws://signaling:8080
    depends_on:
      - signaling
    networks:
      - p2p-network
    restart: unless-stopped

  # WebSocket Signaling Server
  signaling:
    build:
      context: .
      dockerfile: Dockerfile.signaling
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - p2p-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - signaling
    networks:
      - p2p-network
    restart: unless-stopped

networks:
  p2p-network:
    driver: bridge

volumes:
  logs:
