version: '3.8'

services:
  frontend:
    build: .
    container_name: p2p-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SIGNALING_SERVER_URL=ws://signaling:8080
    depends_on:
      - signaling
    networks:
      - p2p-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  signaling:
    build:
      context: .
      dockerfile: Dockerfile.signaling
    container_name: p2p-signaling
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - p2p-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: p2p-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - signaling
    networks:
      - p2p-network
    restart: unless-stopped

networks:
  p2p-network:
    driver: bridge
